stages:
  train:
    #cmd: docker-compose run --rm train
    cmd: python src/train.py experiment=catdog_ex +trainer.log_every_n_steps=5
    deps:
      - src/train.py
      - configs/experiment/finetune.yaml
      #- data/dogs_dataset

  eval:
    #cmd: docker-compose run --rm eval
    cmd: python src/eval.py experiment=catdog_ex +trainer.log_every_n_steps=5
    deps:
      - src/eval.py
      - configs/experiment/finetune.yaml
      #- data/dogs_dataset

  infer:
    #cmd: docker-compose run --rm infer
    cmd: python src/infer.py experiment=catdog_ex +trainer.log_every_n_steps=5
    deps:
      - src/infer.py
      - configs/experiment/finetune.yaml
      #- data/dogs_dataset
