# @package _global_

defaults:
  - override /hydra/sweeper: optuna

#optimized_metric: "val/acc_best"
# We want to optimize for the highest test accuracy
optimization_metric: "val/acc"


hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

 
    storage: null

    # name of the study to persist optimization results
    study_name: null

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # total number of runs that will be executed
    n_trials: 10

   
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 1234
      n_startup_trials: 3 # number of random sampling runs before optimization starts

    # define hyperparameter search space
    params:
      # model.lr: interval(1e-5, 1e-2)
      # model.weight_decay: interval(1e-6, 1e-4)
      # data.batch_size: choice(32, 64, 128)
      model.embed_dim: choice(16, 32, 48)
      model.depth: choice(4, 8)
      model.num_heads: choice(2, 4)
      model.mlp_ratio: interval(2, 4)